# Create TradeExposurebyIndustry.csv
- need export.csv and import download from 
- Delete all datea leave exchange reate for Canada only
- Rename that file as EX.csv for further clean up and massageing then create  Exchange_Rate.csv for Data model

In [1]:

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

Export= pd.read_csv("../RawData/export.csv")
Import= pd.read_csv("../RawData/import.csv")


print(Export.head())
print(Import.head())

   REF_DATE     GEO           DGUID         Estimates  \
0      2000  Canada  2021A000011124  Value of exports
1      2000  Canada  2021A000011124  Value of exports
2      2000  Canada  2021A000011124  Value of exports
3      2000  Canada  2021A000011124  Value of exports
4      2000  Canada  2021A000011124  Value of exports

  North American Industry Classification System (NAICS)      UOM  UOM_ID  \
0                                     All industries     Dollars      81
1    Agriculture, forestry, fishing and hunting [11]     Dollars      81
2  Mining, quarrying, and oil and gas extraction ...     Dollars      81
3                                     Utilities [22]     Dollars      81
4                                  Construction [23]     Dollars      81

  SCALAR_FACTOR  SCALAR_ID       VECTOR COORDINATE        VALUE STATUS  \
0     thousands          3  v1066363891      1.1.1  371595043.0    NaN
1     thousands          3  v1066363892      1.1.2    3188695.0    NaN
2     thousands          3  v1066363893      1.1.3   39803186.0    NaN
3     thousands          3  v1066363894      1.1.4    5290672.0    NaN
4     thousands          3  v1066363895      1.1.5    1534275.0    NaN

   SYMBOL  TERMINATED  DECIMALS
0     NaN         NaN         0
1     NaN         NaN         0
2     NaN         NaN         0
3     NaN         NaN         0
4     NaN         NaN         0
   REF_DATE     GEO           DGUID         Estimates  \
0      2005  Canada  2021A000011124  Value of imports
1      2005  Canada  2021A000011124  Value of imports
2      2005  Canada  2021A000011124  Value of imports
3      2005  Canada  2021A000011124  Value of imports
4      2005  Canada  2021A000011124  Value of imports

  North American Industry Classification System (NAICS)      UOM  UOM_ID  \
0                                     All industries     Dollars      81
1    Agriculture, forestry, fishing and hunting [11]     Dollars      81
2  Mining, quarrying, and oil and gas extraction ...     Dollars      81
3                                     Utilities [22]     Dollars      81
4                                  Construction [23]     Dollars      81

  SCALAR_FACTOR  SCALAR_ID       VECTOR COORDINATE        VALUE STATUS  \
0     thousands          3  v1070721306      1.1.1  363851094.0    NaN
1     thousands          3  v1070721307      1.1.2    1026965.0    NaN
2     thousands          3  v1070721308      1.1.3    2674504.0    NaN
3     thousands          3  v1070721309      1.1.4    4015516.0    NaN
4     thousands          3  v1070721310      1.1.5    2753420.0    NaN

   SYMBOL  TERMINATED  DECIMALS
0     NaN         NaN         0
1     NaN         NaN         0
2     NaN         NaN         0
3     NaN         NaN         0
4     NaN         NaN         0

In [2]:
print(Export["GEO"].unique())

['Canada' 'Census metropolitan area (CMA)'
 "St. John's, Newfoundland and Labrador" 'Halifax, Nova Scotia'
 'Moncton, New Brunswick' 'Saint John, New Brunswick' 'Saguenay, Quebec'
 'Québec, Quebec' 'Sherbrooke, Quebec' 'Trois-Rivières, Quebec'
 'Montréal, Quebec' 'Ottawa-Gatineau, Ontario/Quebec' 'Kingston, Ontario'
 'Belleville - Quinte West, Ontario' 'Peterborough, Ontario'
 'Oshawa, Ontario' 'Toronto, Ontario' 'Hamilton, Ontario'
 'St. Catharines-Niagara, Ontario' 'Kitchener-Cambridge-Waterloo, Ontario'
 'Brantford, Ontario' 'Guelph, Ontario' 'London, Ontario'
 'Windsor, Ontario' 'Barrie, Ontario' 'Greater Sudbury, Ontario'
 'Thunder Bay, Ontario' 'Winnipeg, Manitoba' 'Regina, Saskatchewan'
 'Saskatoon, Saskatchewan' 'Lethbridge, Alberta' 'Calgary, Alberta'
 'Edmonton, Alberta' 'Kelowna, British Columbia'
 'Abbotsford-Mission, British Columbia' 'Vancouver, British Columbia'
 'Victoria, British Columbia' 'Non-Census metropolitan area'
 'Fredericton, New Brunswick' 'Drummondville, Quebec' 'Red Deer, Alberta'
 'Kamloops, British Columbia' 'Chilliwack, British Columbia'
 'Nanaimo, British Columbia']

In [3]:
print(Import["GEO"].unique())

['Canada' 'Census metropolitan area (CMA)'
 "St. John's, Newfoundland and Labrador" 'Halifax, Nova Scotia'
 'Moncton, New Brunswick' 'Saint John, New Brunswick' 'Saguenay, Quebec'
 'Québec, Quebec' 'Sherbrooke, Quebec' 'Trois-Rivières, Quebec'
 'Montréal, Quebec' 'Ottawa-Gatineau, Ontario/Quebec' 'Kingston, Ontario'
 'Belleville - Quinte West, Ontario' 'Peterborough, Ontario'
 'Oshawa, Ontario' 'Toronto, Ontario' 'Hamilton, Ontario'
 'St. Catharines-Niagara, Ontario' 'Kitchener-Cambridge-Waterloo, Ontario'
 'Brantford, Ontario' 'Guelph, Ontario' 'London, Ontario'
 'Windsor, Ontario' 'Barrie, Ontario' 'Greater Sudbury, Ontario'
 'Thunder Bay, Ontario' 'Winnipeg, Manitoba' 'Regina, Saskatchewan'
 'Saskatoon, Saskatchewan' 'Lethbridge, Alberta' 'Calgary, Alberta'
 'Edmonton, Alberta' 'Kelowna, British Columbia'
 'Abbotsford-Mission, British Columbia' 'Vancouver, British Columbia'
 'Victoria, British Columbia' 'Non-Census metropolitan area'
 'Fredericton, New Brunswick' 'Drummondville, Quebec' 'Red Deer, Alberta'
 'Kamloops, British Columbia' 'Chilliwack, British Columbia'
 'Nanaimo, British Columbia']

In [4]:
Export.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35632 entries, 0 to 35631
Data columns (total 16 columns):
 #   Column                                                 Non-Null Count  Dtype
---  ------                                                 --------------  -----
 0   REF_DATE                                               35632 non-null  int64
 1   GEO                                                    35632 non-null  object
 2   DGUID                                                  33532 non-null  object
 3   Estimates                                              35632 non-null  object
 4   North American Industry Classification System (NAICS)  35632 non-null  object
 5   UOM                                                    35632 non-null  object
 6   UOM_ID                                                 35632 non-null  int64
 7   SCALAR_FACTOR                                          35632 non-null  object
 8   SCALAR_ID                                              35632 non-null  int64
 9   VECTOR                                                 35632 non-null  object
 10  COORDINATE                                             35632 non-null  object
 11  VALUE                                                  28310 non-null  float64
 12  STATUS                                                 7322 non-null   object
 13  SYMBOL                                                 0 non-null      float64
 14  TERMINATED                                             0 non-null      float64
 15  DECIMALS                                               35632 non-null  int64
dtypes: float64(3), int64(4), object(9)
memory usage: 4.3+ MB

In [5]:
Import.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30470 entries, 0 to 30469
Data columns (total 16 columns):
 #   Column                                                 Non-Null Count  Dtype
---  ------                                                 --------------  -----
 0   REF_DATE                                               30470 non-null  int64
 1   GEO                                                    30470 non-null  object
 2   DGUID                                                  28874 non-null  object
 3   Estimates                                              30470 non-null  object
 4   North American Industry Classification System (NAICS)  30470 non-null  object
 5   UOM                                                    30470 non-null  object
 6   UOM_ID                                                 30470 non-null  int64
 7   SCALAR_FACTOR                                          30470 non-null  object
 8   SCALAR_ID                                              30470 non-null  int64
 9   VECTOR                                                 30470 non-null  object
 10  COORDINATE                                             30470 non-null  object
 11  VALUE                                                  27815 non-null  float64
 12  STATUS                                                 2655 non-null   object
 13  SYMBOL                                                 0 non-null      float64
 14  TERMINATED                                             0 non-null      float64
 15  DECIMALS                                               30470 non-null  int64
dtypes: float64(3), int64(4), object(9)
memory usage: 3.7+ MB

In [6]:
Export = Export.drop('SYMBOL', axis=1)
Export = Export.drop("TERMINATED", axis=1)

In [7]:
Import = Import.drop('SYMBOL', axis=1)
Import = Import.drop("TERMINATED", axis=1)

In [8]:
Export.isnull().sum()

REF_DATE                                                     0
GEO                                                          0
DGUID                                                     2100
Estimates                                                    0
North American Industry Classification System (NAICS)        0
UOM                                                          0
UOM_ID                                                       0
SCALAR_FACTOR                                                0
SCALAR_ID                                                    0
VECTOR                                                       0
COORDINATE                                                   0
VALUE                                                     7322
STATUS                                                   28310
DECIMALS                                                     0
dtype: int64

In [9]:
Import.isnull().sum()

REF_DATE                                                     0
GEO                                                          0
DGUID                                                     1596
Estimates                                                    0
North American Industry Classification System (NAICS)        0
UOM                                                          0
UOM_ID                                                       0
SCALAR_FACTOR                                                0
SCALAR_ID                                                    0
VECTOR                                                       0
COORDINATE                                                   0
VALUE                                                     2655
STATUS                                                   27815
DECIMALS                                                     0
dtype: int64

In [10]:
variation = Export.nunique()
print(variation)

REF_DATE                                                    25
GEO                                                         44
DGUID                                                       42
Estimates                                                    2
North American Industry Classification System (NAICS)       21
UOM                                                          2
UOM_ID                                                       2
SCALAR_FACTOR                                                2
SCALAR_ID                                                    2
VECTOR                                                    1804
COORDINATE                                                1804
VALUE                                                    12281
STATUS                                                       3
DECIMALS                                                     1
dtype: int64

In [11]:
variation = Import.nunique()
print(variation)

REF_DATE                                                    19
GEO                                                         44
DGUID                                                       42
Estimates                                                    2
North American Industry Classification System (NAICS)       21
UOM                                                          2
UOM_ID                                                       2
SCALAR_FACTOR                                                2
SCALAR_ID                                                    2
VECTOR                                                    1842
COORDINATE                                                1842
VALUE                                                    12514
STATUS                                                       3
DECIMALS                                                     1
dtype: int64

In [12]:
print(Export.columns)

Index(['REF_DATE', 'GEO', 'DGUID', 'Estimates',
       'North American Industry Classification System (NAICS)', 'UOM',
       'UOM_ID', 'SCALAR_FACTOR', 'SCALAR_ID', 'VECTOR', 'COORDINATE', 'VALUE',
       'STATUS', 'DECIMALS'],
      dtype='object')

In [13]:

Export = Export[["REF_DATE", "GEO", "Estimates", "North American Industry Classification System (NAICS)", "VALUE"]]
print(Export)

       REF_DATE                           GEO  \
0          2000                        Canada
1          2000                        Canada
2          2000                        Canada
3          2000                        Canada
4          2000                        Canada
...         ...                           ...
35627      2024  Non-Census metropolitan area
35628      2024  Non-Census metropolitan area
35629      2024  Non-Census metropolitan area
35630      2024  Non-Census metropolitan area
35631      2024  Non-Census metropolitan area

                                Estimates  \
0                        Value of exports
1                        Value of exports
2                        Value of exports
3                        Value of exports
4                        Value of exports
...                                   ...
35627  Number of exporting establishments
35628  Number of exporting establishments
35629  Number of exporting establishments
35630  Number of exporting establishments
35631  Number of exporting establishments

      North American Industry Classification System (NAICS)        VALUE
0                                         All industries     371595043.0
1        Agriculture, forestry, fishing and hunting [11]       3188695.0
2      Mining, quarrying, and oil and gas extraction ...      39803186.0
3                                         Utilities [22]       5290672.0
4                                      Construction [23]       1534275.0
...                                                  ...             ...
35627             Health care and social assistance [62]            66.0
35628            Arts, entertainment and recreation [71]           125.0
35629               Accommodation and food services [72]            47.0
35630  Other services (except public administration) ...           315.0
35631                         Public administration [91]            27.0

[35632 rows x 5 columns]

In [14]:
wide_export = Export.pivot(index=["REF_DATE", "GEO", "North American Industry Classification System (NAICS)"], columns="Estimates", values="VALUE")
wide_export = wide_export.reset_index()

print(wide_export)

Estimates  REF_DATE                                   GEO  \
0              2000  Abbotsford-Mission, British Columbia
1              2000  Abbotsford-Mission, British Columbia
2              2000  Abbotsford-Mission, British Columbia
3              2000  Abbotsford-Mission, British Columbia
4              2000  Abbotsford-Mission, British Columbia
...             ...                                   ...
17811          2024                    Winnipeg, Manitoba
17812          2024                    Winnipeg, Manitoba
17813          2024                    Winnipeg, Manitoba
17814          2024                    Winnipeg, Manitoba
17815          2024                    Winnipeg, Manitoba

Estimates North American Industry Classification System (NAICS)  \
0                       Accommodation and food services [72]
1          Administrative and support, waste management a...
2            Agriculture, forestry, fishing and hunting [11]
3                                             All industries
4                    Arts, entertainment and recreation [71]
...                                                      ...
17811                Real estate and rental and leasing [53]
17812                                   Retail trade [44-45]
17813                 Transportation and warehousing [48-49]
17814                                         Utilities [22]
17815                                   Wholesale trade [41]

Estimates  Number of exporting establishments  Value of exports
0                                         NaN               NaN
1                                         NaN               NaN
2                                         NaN               NaN
3                                         NaN               NaN
4                                         NaN               NaN
...                                       ...               ...
17811                                    17.0            3727.0
17812                                    86.0           48969.0
17813                                    46.0          325949.0
17814                                     NaN          671280.0
17815                                   264.0        12995878.0

[17816 rows x 5 columns]

In [15]:
Import = Import[["REF_DATE", "GEO", "Estimates", "North American Industry Classification System (NAICS)", "VALUE"]]
print(Import)

       REF_DATE                           GEO  \
0          2005                        Canada
1          2005                        Canada
2          2005                        Canada
3          2005                        Canada
4          2005                        Canada
...         ...                           ...
30465      2023  Non-Census metropolitan area
30466      2023  Non-Census metropolitan area
30467      2023  Non-Census metropolitan area
30468      2023  Non-Census metropolitan area
30469      2023  Non-Census metropolitan area

                                Estimates  \
0                        Value of imports
1                        Value of imports
2                        Value of imports
3                        Value of imports
4                        Value of imports
...                                   ...
30465  Number of importing establishments
30466  Number of importing establishments
30467  Number of importing establishments
30468  Number of importing establishments
30469  Number of importing establishments

      North American Industry Classification System (NAICS)        VALUE
0                                         All industries     363851094.0
1        Agriculture, forestry, fishing and hunting [11]       1026965.0
2      Mining, quarrying, and oil and gas extraction ...       2674504.0
3                                         Utilities [22]       4015516.0
4                                      Construction [23]       2753420.0
...                                                  ...             ...
30465             Health care and social assistance [62]           992.0
30466            Arts, entertainment and recreation [71]           738.0
30467               Accommodation and food services [72]          1152.0
30468  Other services (except public administration) ...          2641.0
30469                         Public administration [91]           458.0

[30470 rows x 5 columns]

In [16]:
wide_import = Import.pivot(index=["REF_DATE", "GEO", "North American Industry Classification System (NAICS)"], columns="Estimates", values="VALUE")
wide_import = wide_import.reset_index()

print(wide_import)

Estimates  REF_DATE                                   GEO  \
0              2005  Abbotsford-Mission, British Columbia
1              2005  Abbotsford-Mission, British Columbia
2              2005  Abbotsford-Mission, British Columbia
3              2005  Abbotsford-Mission, British Columbia
4              2005  Abbotsford-Mission, British Columbia
...             ...                                   ...
15230          2023                    Winnipeg, Manitoba
15231          2023                    Winnipeg, Manitoba
15232          2023                    Winnipeg, Manitoba
15233          2023                    Winnipeg, Manitoba
15234          2023                    Winnipeg, Manitoba

Estimates North American Industry Classification System (NAICS)  \
0                       Accommodation and food services [72]
1          Administrative and support, waste management a...
2            Agriculture, forestry, fishing and hunting [11]
3                                             All industries
4                    Arts, entertainment and recreation [71]
...                                                      ...
15230                Real estate and rental and leasing [53]
15231                                   Retail trade [44-45]
15232                 Transportation and warehousing [48-49]
15233                                         Utilities [22]
15234                                   Wholesale trade [41]

Estimates  Number of importing establishments  Value of imports
0                                        19.0              59.0
1                                        19.0            2399.0
2                                       138.0           36147.0
3                                       901.0          691174.0
4                                         5.0              56.0
...                                       ...               ...
15230                                    97.0           13825.0
15231                                   669.0          837175.0
15232                                   163.0          629815.0
15233                                     NaN           81562.0
15234                                   560.0         3332857.0

[15235 rows x 5 columns]

In [17]:
wide_export["industry"] = wide_export["North American Industry Classification System (NAICS)"].str.extract("(\d+)")
wide_export["industry"] = wide_export["industry"].fillna(0).astype(int)
wide_export["industry"] = wide_export["industry"].astype(int)
wide_export.head()

Estimates,REF_DATE,GEO,North American Industry Classification System (NAICS),Number of exporting establishments,Value of exports,industry
0,2000,"Abbotsford-Mission, British Columbia",Accommodation and food services [72],NaN,NaN,72
1,2000,"Abbotsford-Mission, British Columbia","Administrative and support, waste management a...",NaN,NaN,56
2,2000,"Abbotsford-Mission, British Columbia","Agriculture, forestry, fishing and hunting [11]",NaN,NaN,11
3,2000,"Abbotsford-Mission, British Columbia",All industries,NaN,NaN,0
4,2000,"Abbotsford-Mission, British Columbia","Arts, entertainment and recreation [71]",NaN,NaN,71

In [18]:
wide_import["industry"] = wide_import["North American Industry Classification System (NAICS)"].str.extract("(\d+)")
wide_import["industry"] = wide_import["industry"].fillna(0).astype(int)
wide_import["industry"] = wide_import["industry"].astype(int)
wide_import.head()

Estimates,REF_DATE,GEO,North American Industry Classification System (NAICS),Number of importing establishments,Value of imports,industry
0,2005,"Abbotsford-Mission, British Columbia",Accommodation and food services [72],19.0,59.0,72
1,2005,"Abbotsford-Mission, British Columbia","Administrative and support, waste management a...",19.0,2399.0,56
2,2005,"Abbotsford-Mission, British Columbia","Agriculture, forestry, fishing and hunting [11]",138.0,36147.0,11
3,2005,"Abbotsford-Mission, British Columbia",All industries,901.0,691174.0,0
4,2005,"Abbotsford-Mission, British Columbia","Arts, entertainment and recreation [71]",5.0,56.0,71

In [19]:
print(wide_export["industry"].unique())

[72 56 11  0 71 23 52 62 51 31 21 81 54 53 44 48 22 41 61 91 55]

In [20]:
wide_export = wide_export[(wide_export['REF_DATE'] >= 2013) & (wide_export['REF_DATE'] <= 2023)]
wide_export.head()

Estimates,REF_DATE,GEO,North American Industry Classification System (NAICS),Number of exporting establishments,Value of exports,industry
9016,2013,"Abbotsford-Mission, British Columbia","Administrative and support, waste management a...",NaN,7643.0,56
9017,2013,"Abbotsford-Mission, British Columbia","Agriculture, forestry, fishing and hunting [11]",32.0,71539.0,11
9018,2013,"Abbotsford-Mission, British Columbia",All industries,303.0,597215.0,0
9019,2013,"Abbotsford-Mission, British Columbia","Arts, entertainment and recreation [71]",NaN,3.0,71
9020,2013,"Abbotsford-Mission, British Columbia",Construction [23],17.0,4381.0,23

In [21]:
wide_import = wide_import[(wide_import['REF_DATE'] >= 2013) & (wide_import['REF_DATE'] <= 2023)]
wide_import.head()

Estimates,REF_DATE,GEO,North American Industry Classification System (NAICS),Number of importing establishments,Value of imports,industry
6258,2013,"Abbotsford-Mission, British Columbia",Accommodation and food services [72],16.0,70.0,72
6259,2013,"Abbotsford-Mission, British Columbia","Administrative and support, waste management a...",31.0,2394.0,56
6260,2013,"Abbotsford-Mission, British Columbia","Agriculture, forestry, fishing and hunting [11]",172.0,41396.0,11
6261,2013,"Abbotsford-Mission, British Columbia",All industries,1040.0,581814.0,0
6262,2013,"Abbotsford-Mission, British Columbia","Arts, entertainment and recreation [71]",8.0,193.0,71

In [22]:
wide_export = wide_export.dropna(subset=["Value of exports"])
wide_import = wide_import.dropna(subset=["Value of imports"])

In [23]:
merged = pd.merge(wide_export, wide_import, on=["GEO", "REF_DATE", "industry"], how="inner")
merged.head()

Estimates,REF_DATE,GEO,North American Industry Classification System (NAICS)_x,Number of exporting establishments,Value of exports,industry,North American Industry Classification System (NAICS)_y,Number of importing establishments,Value of imports
0,2013,"Abbotsford-Mission, British Columbia","Administrative and support, waste management a...",NaN,7643.0,56,"Administrative and support, waste management a...",31.0,2394.0
1,2013,"Abbotsford-Mission, British Columbia","Agriculture, forestry, fishing and hunting [11]",32.0,71539.0,11,"Agriculture, forestry, fishing and hunting [11]",172.0,41396.0
2,2013,"Abbotsford-Mission, British Columbia",All industries,303.0,597215.0,0,All industries,1040.0,581814.0
3,2013,"Abbotsford-Mission, British Columbia","Arts, entertainment and recreation [71]",NaN,3.0,71,"Arts, entertainment and recreation [71]",8.0,193.0
4,2013,"Abbotsford-Mission, British Columbia",Construction [23],17.0,4381.0,23,Construction [23],86.0,43788.0

In [24]:
merged[["CMA", "Province"]] = merged["GEO"].str.split(",", expand=True)
merged.head()

Estimates,REF_DATE,GEO,North American Industry Classification System (NAICS)_x,Number of exporting establishments,Value of exports,industry,North American Industry Classification System (NAICS)_y,Number of importing establishments,Value of imports,CMA,Province
0,2013,"Abbotsford-Mission, British Columbia","Administrative and support, waste management a...",NaN,7643.0,56,"Administrative and support, waste management a...",31.0,2394.0,Abbotsford-Mission,British Columbia
1,2013,"Abbotsford-Mission, British Columbia","Agriculture, forestry, fishing and hunting [11]",32.0,71539.0,11,"Agriculture, forestry, fishing and hunting [11]",172.0,41396.0,Abbotsford-Mission,British Columbia
2,2013,"Abbotsford-Mission, British Columbia",All industries,303.0,597215.0,0,All industries,1040.0,581814.0,Abbotsford-Mission,British Columbia
3,2013,"Abbotsford-Mission, British Columbia","Arts, entertainment and recreation [71]",NaN,3.0,71,"Arts, entertainment and recreation [71]",8.0,193.0,Abbotsford-Mission,British Columbia
4,2013,"Abbotsford-Mission, British Columbia",Construction [23],17.0,4381.0,23,Construction [23],86.0,43788.0,Abbotsford-Mission,British Columbia

In [25]:
merged["CMA"] = merged["CMA"].replace("Canada", None)
merged["CMA"] = merged["CMA"].replace("Census metropolitan area (CMA)", None)
merged["CMA"] = merged["CMA"].replace("Non-Census metropolitan area", None)
merged.head()

Estimates,REF_DATE,GEO,North American Industry Classification System (NAICS)_x,Number of exporting establishments,Value of exports,industry,North American Industry Classification System (NAICS)_y,Number of importing establishments,Value of imports,CMA,Province
0,2013,"Abbotsford-Mission, British Columbia","Administrative and support, waste management a...",NaN,7643.0,56,"Administrative and support, waste management a...",31.0,2394.0,Abbotsford-Mission,British Columbia
1,2013,"Abbotsford-Mission, British Columbia","Agriculture, forestry, fishing and hunting [11]",32.0,71539.0,11,"Agriculture, forestry, fishing and hunting [11]",172.0,41396.0,Abbotsford-Mission,British Columbia
2,2013,"Abbotsford-Mission, British Columbia",All industries,303.0,597215.0,0,All industries,1040.0,581814.0,Abbotsford-Mission,British Columbia
3,2013,"Abbotsford-Mission, British Columbia","Arts, entertainment and recreation [71]",NaN,3.0,71,"Arts, entertainment and recreation [71]",8.0,193.0,Abbotsford-Mission,British Columbia
4,2013,"Abbotsford-Mission, British Columbia",Construction [23],17.0,4381.0,23,Construction [23],86.0,43788.0,Abbotsford-Mission,British Columbia

In [26]:
merged.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 7854 entries, 0 to 7853
Data columns (total 11 columns):
 #   Column                                                   Non-Null Count  Dtype
---  ------                                                   --------------  -----
 0   REF_DATE                                                 7854 non-null   int64
 1   GEO                                                      7854 non-null   object
 2   North American Industry Classification System (NAICS)_x  7854 non-null   object
 3   Number of exporting establishments                       5358 non-null   float64
 4   Value of exports                                         7854 non-null   float64
 5   industry                                                 7854 non-null   int32
 6   North American Industry Classification System (NAICS)_y  7854 non-null   object
 7   Number of importing establishments                       7360 non-null   float64
 8   Value of imports                                         7854 non-null   float64
 9   CMA                                                      7161 non-null   object
 10  Province                                                 7161 non-null   object
dtypes: float64(4), int32(1), int64(1), object(5)
memory usage: 705.6+ KB

In [27]:
merged['total_trade'] = merged['Value of exports'] + merged['Value of imports']
merged.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 7854 entries, 0 to 7853
Data columns (total 12 columns):
 #   Column                                                   Non-Null Count  Dtype
---  ------                                                   --------------  -----
 0   REF_DATE                                                 7854 non-null   int64
 1   GEO                                                      7854 non-null   object
 2   North American Industry Classification System (NAICS)_x  7854 non-null   object
 3   Number of exporting establishments                       5358 non-null   float64
 4   Value of exports                                         7854 non-null   float64
 5   industry                                                 7854 non-null   int32
 6   North American Industry Classification System (NAICS)_y  7854 non-null   object
 7   Number of importing establishments                       7360 non-null   float64
 8   Value of imports                                         7854 non-null   float64
 9   CMA                                                      7161 non-null   object
 10  Province                                                 7161 non-null   object
 11  total_trade                                              7854 non-null   float64
dtypes: float64(5), int32(1), int64(1), object(5)
memory usage: 767.0+ KB

In [28]:
merged = merged.drop(merged[merged["GEO"] == "Canada"].index)
merged = merged.drop(merged[merged["GEO"] == "None"].index)

merged.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 7623 entries, 0 to 7853
Data columns (total 12 columns):
 #   Column                                                   Non-Null Count  Dtype
---  ------                                                   --------------  -----
 0   REF_DATE                                                 7623 non-null   int64
 1   GEO                                                      7623 non-null   object
 2   North American Industry Classification System (NAICS)_x  7623 non-null   object
 3   Number of exporting establishments                       5127 non-null   float64
 4   Value of exports                                         7623 non-null   float64
 5   industry                                                 7623 non-null   int32
 6   North American Industry Classification System (NAICS)_y  7623 non-null   object
 7   Number of importing establishments                       7129 non-null   float64
 8   Value of imports                                         7623 non-null   float64
 9   CMA                                                      7161 non-null   object
 10  Province                                                 7161 non-null   object
 11  total_trade                                              7623 non-null   float64
dtypes: float64(5), int32(1), int64(1), object(5)
memory usage: 744.4+ KB

In [29]:
merged = merged[merged["Province"].notna()]

In [30]:
print(merged["Province"].unique())

[' British Columbia' ' Ontario' ' Alberta' ' Nova Scotia' ' New Brunswick'
 ' Quebec' ' Ontario/Quebec' ' Saskatchewan' ' Newfoundland and Labrador'
 ' Manitoba']

In [31]:
# print(df3["Province"].unique())

In [32]:
merged["Province"] = merged["Province"].replace(' British Columbia', 'British Columbia')
merged["Province"] = merged["Province"].replace(' Ontario', 'Ontario')
merged["Province"] = merged["Province"].replace(' Alberta', 'Alberta')
merged["Province"] = merged["Province"].replace(' Nova Scotia', 'Nova Scotia')
merged["Province"] = merged["Province"].replace(' New Brunswick', 'New Brunswick')
merged["Province"] = merged["Province"].replace(' Quebec', 'Quebec')
merged["Province"] = merged["Province"].replace(' Saskatchewan', 'Saskatchewan')
merged["Province"] = merged["Province"].replace( ' Newfoundland and Labrador', 'Newfoundland and Labrador')
merged["Province"] = merged["Province"].replace( ' Manitoba', 'Manitoba')
merged["Province"] = merged["Province"].replace( ' Ontario/Quebec', 'Ontario')

In [33]:
merged.count()

Estimates
REF_DATE                                                   7161
GEO                                                        7161
North American Industry Classification System (NAICS)_x    7161
Number of exporting establishments                         4665
Value of exports                                           7161
industry                                                   7161
North American Industry Classification System (NAICS)_y    7161
Number of importing establishments                         6667
Value of imports                                           7161
CMA                                                        7161
Province                                                   7161
total_trade                                                7161
dtype: int64

In [34]:
merged = merged.drop('North American Industry Classification System (NAICS)_x', axis=1)
merged = merged.drop('North American Industry Classification System (NAICS)_y', axis=1)

# merged.head()

In [35]:
merged = (
    merged.groupby(["Province", "industry", "REF_DATE"])["total_trade","Value of exports", "Value of imports"
]
    .sum()        # or .mean(), depending on what you want
    .reset_index()
)
merged.head()

C:\Users\dimpa\AppData\Local\Temp\ipykernel_21876\3070568482.py:2: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  merged.groupby(["Province", "industry", "REF_DATE"])["total_trade","Value of exports", "Value of imports"

Estimates,Province,industry,REF_DATE,total_trade,Value of exports,Value of imports
0,Alberta,0,2013,139364164.0,92750112.0,46614052.0
1,Alberta,0,2014,153658120.0,103631865.0,50026255.0
2,Alberta,0,2015,120889390.0,79154756.0,41734634.0
3,Alberta,0,2016,104104281.0,64621025.0,39483256.0
4,Alberta,0,2017,125464737.0,85402212.0,40062525.0

In [36]:
# Step : Export to Csv
merged.to_csv("../Src/TradeExposurebyIndustry.csv", index=False)
print("TradeExposureByIndustry.csv generated...")

TradeExposureByIndustry.csv generated...

In [37]:
# trade = pd.merge(merged, df3, on=["Province", "REF_DATE", "industry"], how="left")
# trade.head()